FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build-env
WORKDIR /app

COPY ./src/ ./
RUN dotnet publish ./NeverAlone.Console.UserMonitorNotifications/NeverAlone.Console.UserMonitorNotifications.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "NeverAlone.Console.UserMonitorNotifications.dll"]